package com.mascotas.sda.util;

public enum PermisosRol {
    READ_ALL_GRUPOS,
    READ_ONE_GRUPOS,
    CREATE_ONE_GRUPOS,
    UPDATE_ONE_GRUPOS,
    DISABLE_ONE_GRUPOS,

    READ_ALL_ALUMNOS,
    READ_ONE_ALUMNOS,
    CREATE_ONE_ALUMNOS,
    UPDATE_ONE_ALUMNOS,
    DISABLE_ONE_ALUMNOS,

    READ_ALL_CONVOCATORIA,
    READ_ONE_CONVOCATORIA,
    CREATE_ONE_CONVOCATORIA,
    UPDATE_ONE_CONVOCATORIA,
    DISABLE_ONE_CONVOCATORIA,
}